Imports

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import os

Create dataframe and initialize X and Y

In [34]:
path = "data/ucl_fantasy_dataset.csv"

base_dir = os.path.dirname(os.path.abspath(os.getcwd()))

df = pd.read_csv(os.path.join(base_dir, path))

X = df.drop(columns=["fantasy_points"])

y = df["fantasy_points"]

Print first 5 rows to see some data

In [38]:
df.head(5)

            player              team  ... fantasy_points matchday
0     Mislav Oršić  Dinamo Zagreb hr  ...              6        1
1     Dario Špikić  Dinamo Zagreb hr  ...              1        1
2   Bruno Petković  Dinamo Zagreb hr  ...              5        1
3      Josip Drmić  Dinamo Zagreb hr  ...              1        1
4  Robert Ljubicic  Dinamo Zagreb hr  ...              2        1

[5 rows x 41 columns]

Display X and y

In [39]:
X.head(5)

            player              team  ... fantasy_position matchday
0     Mislav Oršić  Dinamo Zagreb hr  ...              FWD        1
1     Dario Špikić  Dinamo Zagreb hr  ...              MID        1
2   Bruno Petković  Dinamo Zagreb hr  ...              FWD        1
3      Josip Drmić  Dinamo Zagreb hr  ...              FWD        1
4  Robert Ljubicic  Dinamo Zagreb hr  ...              FWD        1

[5 rows x 40 columns]

In [40]:
y.head(5)

0    6
1    1
2    5
3    1
4    2
Name: fantasy_points, dtype: int64

From the X matrix, we can see that there is a lot of significant and insignificant data that are in a nonumeric format.