Imports

In [99]:
%pip install -q matplotlib seaborn xgboost scikit-learn pandas numpy

Note: you may need to restart the kernel to use updated packages.

In [100]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import os

Create dataframe and initialize X and Y

In [101]:
path = "data/modeling_dataset.csv"

base_dir = os.path.dirname(os.path.abspath(os.getcwd()))

df = pd.read_csv(os.path.join(base_dir, path))

X = df.drop(columns=["fantasy_points"])

# bucket points into 4 ordered tiers: bench / ok / good / haul                                                                        
y = pd.cut(df["fantasy_points"].clip(lower=0),                                                                                        
            bins=[-1, 1, 4, 8, 100],                   
            labels=[0, 1, 2, 3]).astype(int)

Print first 5 rows to see some data

In [102]:
df.head(5)

            player         team  ... regular_recently fantasy_points
0  Aaron Anselmino  Dortmund de  ...                0              9
1  Aaron Anselmino  Dortmund de  ...                0              1
2    Aaron Bouwman      nl Ajax  ...                0              1
3       Aaron Mooy   Celtic sct  ...                0              1
4       Aaron Mooy   Celtic sct  ...                0              1

[5 rows x 91 columns]

Display X and y

In [103]:
X.head(5)

            player         team  ... minutes_last3_sum regular_recently
0  Aaron Anselmino  Dortmund de  ...               6.0                0
1  Aaron Anselmino  Dortmund de  ...              96.0                0
2    Aaron Bouwman      nl Ajax  ...              90.0                0
3       Aaron Mooy   Celtic sct  ...              23.0                0
4       Aaron Mooy   Celtic sct  ...              48.0                0

[5 rows x 90 columns]

In [104]:
y.head(5)

0    3
1    0
2    0
3    0
4    0
Name: fantasy_points, dtype: int32

From the X matrix, we can see that there is a lot of significant and insignificant data that are in a nonumeric format.

In [105]:
# Preprocessing for converting text columns into numeric 
# drop name, date, season, team, opponent (text columns)
X_clean = X.drop(columns=["player", "date", "season", "team", "opponent"])

# turning home and away into binary values
X_clean["home_away"] = (X_clean["home_away"] == "home").astype(int)

# every position column, marked 1 if it matches that row and 0 otherwise  
X_clean = pd.get_dummies(X_clean, columns=["fantasy_position"], drop_first=True)                                                      
X_clean = X_clean.astype(float) 

print("Shape: ", X_clean.shape)
print("non-numeric columns left", X_clean.select_dtypes(exclude="number").columns.tolist())
X_clean.head()

Shape:  (16549, 87)
non-numeric columns left []

   home_away  matchday  ...  fantasy_position_GK  fantasy_position_MID
0        1.0      10.0  ...                  0.0                   0.0
1        1.0      13.0  ...                  0.0                   0.0
2        0.0      14.0  ...                  0.0                   0.0
3        1.0       7.0  ...                  0.0                   1.0
4        1.0       9.0  ...                  0.0                   1.0

[5 rows x 87 columns]

In [106]:
# train test split
order = df.sort_values(by="date").index
X_sorted = X_clean.loc[order].reset_index(drop=True)
y_sorted = y.loc[order].reset_index(drop=True)

# train on first 80% of games and last 20% for testing
split_indx = int(len(X_sorted) * 0.8)
X_train, X_test = X_sorted.iloc[:split_indx], X_sorted.iloc[split_indx:]
y_train, y_test = y_sorted.iloc[:split_indx], y_sorted.iloc[split_indx:]

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (13239, 87)
Testing set shape: (3310, 87)

Train Multiple Multiple linear Regression Model

In [107]:
model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

Evaluate the model

In [108]:
print("MAE:", mean_absolute_error(y_test, y_pred))

print("MSE:", mean_squared_error(y_test, y_pred))

print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

print("R2:", r2_score(y_test, y_pred))

MAE: 0.6594749372712517
MSE: 0.6491882501338764
RMSE: 0.8057221916602995
R2: 0.15603432223659486